language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tfreebern2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tfreebern2/docker-react npm run test